language: node_js
node_js: 
  - "node"
addons:
  firefox: "48.0"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "echo \"Extracting firefox and setting PATH variable...\""
  - "tar -xjf /tmp/firefox-48.0.tar.bz2 --directory /tmp"
  - "export PATH=\"/tmp/firefox:$PATH\""
  - "echo \"Using firefox version `firefox --version`\""
